// Code generated by go generate; DO NOT EDIT.
package multicodec

// Codecs maps the name of a codec to its type
var Codecs = map[string]Codec{ 
{{ range .Codecs }}{{ if not .IsDeprecated }}"{{ .Name }}": {{ .VarName }},
{{ end }}{{ end }}
}

// CodecToStr maps the numeric codec to its name
var CodecToStr = map[Codec]string{
{{ range .Codecs }}{{ if not .IsDeprecated }}{{ .VarName }}: "{{ .Name }}",
{{ end }}{{ end }}
}