// Code generated by go generate; DO NOT EDIT.
package multicodec
{{ $ := . }}
{{ range .Tags }}
// {{ . | ToTitle }}Codec maps the name of a codec with tag "{{ . }}" to its type
var {{ . | ToTitle }}Codec = map[string]Codec{ 
{{ range index $.CodecsByTag . }}{{ if not .IsDeprecated }}"{{ .Name }}": {{ .VarName }},
{{ end }}{{ end }}
}

// {{ . | ToTitle }}CodecToStr maps the numeric codec with tag "{{ . }}" to its name
var {{ . | ToTitle }}CodecToStr = map[Codec]string{
{{ range index $.CodecsByTag . }}{{ if not .IsDeprecated }}{{ .VarName }}: "{{ .Name }}",
{{ end }}{{ end }}
}

{{ end }}