name: "Multicodecs submodule update"
on:
  schedule:
    - cron: "7 0 * * *" # Every day at 7 minutes after midnight (everyone runs at 00:00, let's be nice to GH)

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Generating files
        run: go generate

      - name: Creating Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Autoupdate multicodec constants
          body: "Detected changes in the multicodec table @dennis-tra."
          commit-message: Update multicodec constants
          branch: autoupdate/multicodec
          delete-branch: true
